// ------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
// Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
// ------------------------------------------------------------
use std::fs::{self};

use windows_bindgen::bindgen;

fn main() {
    // Flat-layout (Windows.Win32.*) SF winmd generated by the Rust rust-metadata
    // tool. Required by the new (git) windows-bindgen, whose bundled reference
    // metadata uses the flat Windows.Win32 layout rather than the dotnet
    // win32metadata Windows.Win32.Foundation.* layout.
    let winmd = "./crates/tools/api/winmd/Microsoft.ServiceFabric.winmd";
    // create output dir if not exist
    fs::create_dir_all("crates/libs/com/src/Microsoft/ServiceFabric/").unwrap();

    {
        // The regenerated winmd is single-rooted under `Microsoft` (FILETIME is
        // defined SF-locally), so the new windows-bindgen `--package` writer can
        // emit the per-namespace layout into the mssf-com crate.
        let out_file = "crates/libs/com/";

        let args = vec![
            "--in",
            winmd,
            "--in",
            "default",
            "--out",
            out_file,
            "--package",
            "--filter",
        ];
        // Note: winmd currently does not contain C free standing functions,
        // if they are added in the future, we may need to add more filters here.
        let filter_types = vec!["Microsoft.ServiceFabric.FabricTypes"];
        let filter_common = vec![
            "Microsoft.ServiceFabric.FabricCommon", // include fabric types
        ];

        let filter_runtime = vec![
            "Microsoft.ServiceFabric.FabricRuntime", // include fabric types
        ];

        let filter_client = vec![
            "Microsoft.ServiceFabric.FabricClient", // include fabric types
        ];

        bindgen(
            args.into_iter()
                .chain(filter_types)
                .chain(filter_common)
                .chain(filter_runtime)
                .chain(filter_client),
        );
    }

    // The new windows-bindgen projects scoped (newtype) enums with their variants
    // as *associated* constants (`impl FABRIC_X { pub const FABRIC_X_Y: Self = Self(n); }`),
    // referenced as `FABRIC_X::FABRIC_X_Y`. The old dotnet toolchain instead emitted
    // free module-level constants (`pub const FABRIC_X_Y: FABRIC_X = ...;`), which is
    // how mssf-core references them. Emit those free-const aliases here so the ergonomic
    // `FabricTypes::FABRIC_X_Y` spelling keeps working alongside the newtype.
    for ns in [
        "FabricTypes",
        "FabricCommon",
        "FabricClient",
        "FabricRuntime",
    ] {
        let path = format!("crates/libs/com/src/Microsoft/ServiceFabric/{ns}/mod.rs");
        emit_enum_const_aliases(&path);
    }
}

/// Appends free module-level constant aliases for every scoped-enum associated
/// constant in `path` (see call site for rationale).
fn emit_enum_const_aliases(path: &str) {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {path}: {e}"));

    let mut current_enum: Option<&str> = None;
    let mut aliases = String::new();
    for line in text.lines() {
        // Top-level `impl NAME {` (a plain identifier — excludes `impl Trait for T`,
        // generic impls, and `impl Default for ...`). Only scoped enums carry
        // `pub const X: Self = Self(..)` members, so interface/struct impls yield none.
        if let Some(name) = line.strip_prefix("impl ").and_then(|s| s.strip_suffix(" {")) {
            if !name.is_empty() && name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_') {
                current_enum = Some(name);
                continue;
            }
        }
        if line == "}" {
            current_enum = None;
            continue;
        }
        if let Some(en) = current_enum {
            let trimmed = line.trim_start();
            if let Some(rest) = trimmed.strip_prefix("pub const ") {
                // Enum variants are `pub const NAME: Self = Self(..)`. rustfmt may
                // wrap long declarations anywhere (even between `NAME:` and `Self`),
                // so take the identifier up to the first `:`. Skip `pub const fn`
                // helpers (flag enums).
                if !rest.starts_with("fn ") {
                    if let Some((name, _)) = rest.split_once(':') {
                        let name = name.trim();
                        if !name.is_empty()
                            && name.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'_')
                        {
                            aliases.push_str(&format!("pub const {name}: {en} = {en}::{name};\n"));
                        }
                    }
                }
            }
        }
    }

    if aliases.is_empty() {
        return;
    }

    let mut out = text;
    out.push_str(
        "\n// Free module-level aliases for scoped-enum variants (see tools_api). This\n\
         // restores the old dotnet-metadata spelling `FabricTypes::FABRIC_X_Y` in\n\
         // addition to the newtype's associated const `FABRIC_X::FABRIC_X_Y`.\n",
    );
    out.push_str(&aliases);
    fs::write(path, out).unwrap_or_else(|e| panic!("write {path}: {e}"));
}

