// Bindings generated by `windows-bindgen` 0.61.1

#[cfg(feature = "ServiceFabric_FabricClient")]
pub mod FabricClient;
#[cfg(feature = "ServiceFabric_FabricCommon")]
pub mod FabricCommon;
#[cfg(feature = "ServiceFabric_FabricRuntime")]
pub mod FabricRuntime;
#[cfg(feature = "ServiceFabric_FabricTypes")]
pub mod FabricTypes;
