[package]
name = "tools_api"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
serde = "1.0.136"
windows-bindgen = "0.51"
windows-metadata = "0.51"
#windows-targets = "0.51"
#windows-core = "0.51"