[package]
name = "fabric_helper"
version = "0.2.0"
edition = "2018"

[dependencies.windows]
version = "0.41.0"
features = [
    "implement",
    "interface"
]

[dependencies.service-fabric-rs]
path = "../../../"
features = [
    "implement"
]