version: '3.8'

services:
  onebox:
    build:
      context: .
      dockerfile: Dockerfile
      target: onebox
    privileged: true
    ports:
      - "19080:19080"
      - "19000:19000"
  repo:
    build:
      context: .
      dockerfile: Dockerfile
      target: repo
    volumes:
      - ../:/workspaces/repo # repo dir
      - ~/.ssh:/root/.ssh:ro # git creds
    depends_on:
      - onebox
    
  
