[package]
name = "samples_echomain"
version = "0.0.1"
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "*"
ctrlc = { version = "3.0", features = ["termination"] }
tokio = { version = "1", features = ["full"] }

[dependencies.windows]
version = "0.43"
features = [
    "implement"
]

[dependencies.service-fabric-rs]
path = "../../../"
features = [
    "implement"
]

[dependencies.fabric_ext]
path = "../../../crates/fabric/ext"