[package]
name = "samples_echomain"
version = "0.0.1"
edition = "2018"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
serde.workspace = true
serde_derive.workspace = true
mssf-core.workspace = true
