[package]
name = "samples_echomain"
version = "0.0.1"
edition = "2018"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { version = "1", features = ["full"] }
serde = "*"
serde_derive = "*"

[dependencies.mssf-core]
path = "../../libs/core"
